#pragma config(Motor,  port2,           rightMotor,    tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port3,           leftMotor,     tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


task main()
{
	while (1 == 1){
		motor[leftMotor] = vexRT[Ch3]; // left joystick y value
		motor[rightMotor] = vexRT[Ch2]; // right joystick y value
	}
}
