#pragma config(Motor,  port2,           rightMotor,    tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port3,           leftMotor,     tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


task main()
{
	// Initialize User Control using Infinite Loop
	while (1 == 1)
	{
		/*
			Motor Power Values (-127 to 127 inclusive) are set to the values of the joysticks
			in a tank configuration to control drive train
		*/
		//motor[leftMotor] = vexRT[Ch3]; // Left Joystick Y value
		//motor[rightMotor] = vexRT[Ch2]; // Right Joystick Y value


		// Future Drive Train Code (Arcade Control)
		// Turn Left when no forward or backward input
		if (vexRT[Ch4] < 0 && vexRT[Ch2] == 0)
		{
			motor[leftMotor] = -vexRT[Ch4];
			motor[rightMotor] = -vexRT[Ch4];
		}

		// Turn Right when no forward or backward input
		if (vexRT[Ch4] > 0 && vexRT[Ch2] == 0)
		{
			motor[leftMotor] = -vexRT[Ch4];
			motor[rightMotor] = -vexRT[Ch4];
		}
		//Turn Left while Moving
		if(vexRT[Ch4] < 0 && vexRT[Ch2] != 0)
		{
			motor[leftMotor] = -vexRT[Ch2] / 2;
			motor[rightMotor] = vexRT[Ch2];
		}
		//Turn Right while Moving
		if(vexRT[Ch4] > 0 && vexRT[Ch2] != 0)
		{
			motor[leftMotor] = vexRT[Ch2];
			motor[rightMotor] = -vexRT[Ch2] / 2;
		}
		// Forward/Backward Control
		if (vexRT[Ch2] != 0 && vexRT[Ch4] == 0)
		{
			motor[leftMotor] = -vexRT[Ch2];
			motor[rightMotor] = vexRT[Ch2];
		}
	}
}
