#pragma config(Motor,  port2,           rightMotor,    tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port3,           leftMotor,     tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port4,           baseArmMotor,  tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port5,           jointArmMotor, tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port6,           clawServo1,    tmotorServoStandard, openLoop)
#pragma config(Motor,  port7,           clawServo2,    tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	// Initialize User Control using Infinite Loop
	while (1 == 1)
	{
		// Drive Train Code (Split Right Arcade Control); Input from both joysticks

		//Checks if both joysticks are being used, then runs split arcade control
		if(vexRT[Ch2] != 0 && vexRT[Ch4] != 0)
    	{
				motor[leftMotor]  = (-vexRT[Ch2] - vexRT[Ch4])/2;  // (y + x)/2
    		motor[rightMotor] = (-vexRT[Ch2] + vexRT[Ch4])/2;  // (y - x)/2
  		}
  		/*
  		Because values are averaged, when only one stick is used,
  		the maximum speeds of the motors are half of the sticks' maximum inputs.
  		Thise if and else statements counteract this issue by only applying the
  		average when it is turning, and only forward and backward input when it is not.
  		*/
  		else
  		{
  			motor[leftMotor] = -vexRT[Ch2];
  			motor[rightMotor] = -vexRT[Ch2];
  		}

  		//Main arm motor control

  		//inputs 65 to base motor when 5U button is pressed
  		if(vexRT[Btn5U] == 1)
  		{
  			motor[baseArmMotor] = 65;
  		}
  		//inputs -65 to base motor when 5D button is pressed
  		else if(vexRT[Btn5D] == 1)
  		{
  			motor[baseArmMotor] = -65;
  		}
  		else
  		{
  			motor[baseArmMotor] = 0;
  		}

  		 //inputs 65 to joint motor when 6U button is pressed
  		if(vexRT[Btn6U] == 1)
  		{
  			motor[jointArmMotor] = 65;
  		}

  		//inputs -65 to joint motor when 6D button is pressed
  		else if(vexRT[Btn6D] == 1)
  		{
  			motor[jointArmMotor] = -65;
  		}
  		else
  		{
  			motor[jointArmMotor] = 0;
  		}

  		//code for claw open and close


  }
}
