#pragma config(Motor,  port2,           rightMotor,    tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port3,           leftMotor,     tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	// Initialize User Control using Infinite Loop
	while (1 == 1)
	{
		// Drive Train Code (Split Right Arcade Control)
    motor[leftMotor]  = (vexRT[Ch2] - vexRT[Ch4])/2;  // (y + x)/2
    motor[rightMotor] = (vexRT[Ch2] + vexRT[Ch4])/2;  // (y - x)/2
  }
}
